// Generated by CoffeeScript 1.6.2
(function() {
  var Crypto, Express, Faye, Http, Path, Redis, app, bayeux, faye, gravatar, redis, server;

  Express = require('express');

  Http = require('http');

  Path = require('path');

  Faye = require('faye');

  Crypto = require('crypto');

  Redis = require('redis');

  redis = Redis.createClient();

  bayeux = new Faye.NodeAdapter({
    mount: '/faye',
    timeout: 45
  });

  faye = bayeux.getClient();

  app = Express();

  app.set('port', process.env.PORT || 3000);

  app.set('views', __dirname + '/views');

  app.set('view engine', 'ejs');

  app.use(Express.favicon());

  app.use(Express.logger('dev'));

  app.use(Express.bodyParser());

  app.use(Express.methodOverride());

  app.use(Express.cookieParser('your secret here'));

  app.use(Express.session());

  app.use(app.router);

  app.use(require('less-middleware')({
    src: __dirname + '/public'
  }));

  app.use(Express["static"](Path.join(__dirname, 'public')));

  if ('development' === app.get('env')) {
    app.use(Express.errorHandler());
  }

  /* Helpers
  */


  gravatar = function(email) {
    return Crypto.createHash('md5').update(email.toLowerCase().trim()).digest('hex');
  };

  /* Routes
  */


  app.get('/', function(request, response) {
    return response.render('index');
  });

  app.post('/chat', function(request, response) {
    var email, room;

    email = request.body.email;
    room = request.body.room;
    console.log(room);
    return redis.llen("chat:" + room, function(error, message_count) {
      return redis.lrange("chat:" + room, 0, message_count, function(error, messages) {
        return response.render('chat', {
          email: email,
          room: room,
          gravatar: gravatar(email),
          messages: messages
        });
      });
    });
  });

  app.post('/message', function(request, response) {
    var body, email, payload, room;

    email = request.body.email;
    body = request.body.body;
    room = request.body.room;
    payload = {
      email: email,
      body: body,
      gravatar: gravatar(email),
      timestamp: new Date().toString()
    };
    redis.lpush("chat:" + room, JSON.stringify(payload));
    faye.publish("/chat-messages/" + room, payload);
    return response.send(payload);
  });

  /* Server Configuration
  */


  server = Http.createServer(app);

  bayeux.attach(server);

  server.listen(app.get('port'), function() {
    return console.log("Express server listening on port " + (app.get('port')));
  });

}).call(this);
