// Generated by CoffeeScript 1.6.2
(function() {
  var crypto, db, redis;

  crypto = require('crypto');

  redis = require('redis');

  db = redis.createClient();

  exports.index = function(request, response) {
    var baseURL, email, gravatar;

    email = request.body.email;
    baseURL = "https://secure.gravatar.com/avatar/";
    gravatar = baseURL + crypto.createHash('md5').update(email.toLowerCase().trim()).digest('hex');
    return db.llen("chat", function(error, message_count) {
      return db.lrange("chat", 0, message_count, function(error, messages) {
        return response.render('chat', {
          email: email,
          gravatar: gravatar,
          messages: messages
        });
      });
    });
  };

  exports.message = function(request, response) {
    var email, message, payload;

    email = request.body.email;
    message = request.body.message;
    payload = {
      email: email,
      message: message
    };
    db.lpush('chat', JSON.stringify(payload));
    return response.send(200);
  };

}).call(this);
