// Generated by CoffeeScript 1.6.2
(function() {
  var crypto;

  crypto = require('crypto');

  exports.index = function(request, response) {
    var baseURL, email, gravatar;

    email = request.body.email;
    baseURL = "https://secure.gravatar.com/avatar/";
    gravatar = baseURL + crypto.createHash('md5').update(email.toLowerCase().trim()).digest('hex');
    return response.render('chat', {
      email: email,
      gravatar: gravatar
    });
  };

}).call(this);
