// Generated by CoffeeScript 1.6.2
(function() {
  exports.index = function(request, response) {
    var email;

    email = request.body.email;
    return response.render('chat', {
      email: email
    });
  };

}).call(this);
